services:
  exam.web:
    image: exam.web
    build:
      context: src
      dockerfile: Exam.Web/Dockerfile
    environment:
      Database__ConnectionString: 'Host=postgres;Database=postgres;User Id=postgres;Password=postgres'
    ports:
      - '8080:8080'
      - '8081:8081'
  
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
